server:
  port: 8089

spring:
  application:
    name: offline-analysis-service
    
hadoop:
  cluster: localhost:9000
  
mysql:
  url: jdbc:mysql://localhost:3306/x_analysis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  username: root
  password: root

logging:
  level:
    com.x.offline.analysis.service: debug