server:
  port: 9000

spring:
  application:
    name: api-gateway-service
    
  cloud:
    gateway:
      routes:
        - id: manage-service
          uri: http://localhost:8080
          predicates:
            - Path=/manage/**
        - id: device-service
          uri: http://localhost:8084
          predicates:
            - Path=/device/**

logging:
  level:
    com.x.api.gateway.service: debug