server:
  port: 8085

spring:
  application:
    name: data-collection-service-2
  kafka:
    bootstrap-servers: kafka1:29092,kafka2:29093,kafka3:29094
    consumer:
      group-id: data-collection-group-2
  iotdb:
    url: iotdb-node2
    host: 6667
    username: root
    password: root
    max-size: 100

# gRPC配置
grpc:
  server:
    port: 9093

logging:
  level:
    com.x.data.collection.service: info