server:
  port: 8087

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# gRPC配置
grpc:
  server:
    port: 9092

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.x.auth.service.entity

logging:
  level:
    com.x.auth.service: debug