server:
  port: 8085

spring:
  application:
    name: data-collection-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: data-collection-group
  iotdb:
    url: 127.0.0.1
    host: 6667
    username: root
    password: root

# gRPC配置
grpc:
  server:
    port: 9093

logging:
  level:
    com.x.data.collection.service: debug
