server:
  port: 8081

spring:
  application:
    name: repository-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_repository?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.x.repository.service.entity

logging:
  level:
    com.x.repository.service: debug