server:
  port: 8086

spring:
  application:
    name: data-sync-service
    
iotdb:
  host: localhost
  port: 6667
  username: root
  password: root
  
hadoop:
  hdfs:
    url: hdfs://localhost:9000

logging:
  level:
    com.x.data.sync.service: debug