server:
  port: 8090

spring:
  application:
    name: alert-notice-service
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
mysql:
  url: jdbc:mysql://localhost:3306/x_alert?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  username: root
  password: root

logging:
  level:
    com.x.alert.notice.service: debug