server:
  port: 8092

spring:
  application:
    name: file-service
    
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

logging:
  level:
    com.x.file.service: debug